### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by kedarbhide** [pencil-code/pencil-code#14]
I'm using latest version of PENCIL code from GitHub. It works fine on our workstation. When I try to compile it on supercomputing facility it is giving following error. Our workstation works on CentOS 6.3 where as supercomputing facility has CentOS 6.2. Previous version of PENCIL code worked fine on both the systems. I'm using mpif90 compiler.

mpif.h:549.16:
    Included at mpicomm_double.f90:55:

```
   integer*8 MPI_DISPLACEMENT_CURRENT
            1
```

Error: Nonstandard type declaration INTEGER*8 at (1)
mpif.h:550.42:
    Included at mpicomm_double.f90:55:

```
   PARAMETER (MPI_DISPLACEMENT_CURRENT=-54278278)
                                      1
```

Error: Symbol 'mpi_displacement_current' at (1) has no IMPLICIT type
make[2]: **\* [mpicomm_double.o] Error 1
make[2]: Leaving directory `/home/external/iitb/kedarb/pencil-code/samples/2d-te                                                                                             sts/2d_methane_flame/8_proc_parallel/src'
make[1]: *** [code] Error 2
make[1]: Leaving directory`/home/external/iitb/kedarb/pencil-code/samples/2d-te                                                                                             sts/2d_methane_flame/8_proc_parallel/src'
make: **\* [default_to_be] Error 2
'make -j FFLAGS_DOUBLE=-fdefault-real-8 -fdefault-double-8 CFLAGS_DOUBLE=-DDOUBL                                                                                             E_PRECISION LD_MPI= CFLAGS_FFTW3= FFLAGS_FFTW3= LD_FFTW3= CFLAGS_FFTW2= FFLAGS_F                                                                                             FTW2= LD_FFTW2= FC=mpif90 F77=mpif77 FFLAGS=-O FSTD_95=-std=f95 FSTD_2003=-std=f                                                                                             2003 CC=mpicc CFLAGS=-DFUNDERSC=1 default_to_be' failed: <>

**Comment by PABourdin** [comment]
This error indicates you have an older MPI library that does not follow the Fortran 95 standard strictly, which we require. I would need to see your full error output in order to help resolving the issue.
